config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
   # Defines the root path route ("/")
   # root "articles#index"
   get '/', to: "academic#index"
   get '/faculties', to: "faculties#index", as: 'all_faculties'
   get "/faculties/new", to: "faculties#new", as: 'new_faculty'
   post "/faculties", to: "faculties#create" 
 
   get '/faculties/:id', to: "faculties#show"
   get '/faculties/:id/edit', to: 'faculties#edit', as: 'edit_faculty'
   patch '/faculties/:id', to: 'faculties#update', as: 'update_faculty'
   delete '/faculties/:id', to: 'faculties#destroy'
   delete '/faculties/', to: 'faculties#destroy'

   get '/courses', to: "courses#index"
   get '/courses/:id', to: "courses#show", as: 'course'
   get '/courses/:id/edit', to: 'courses#edit', as: 'edit_course'
   patch '/courses/:id', to: 'courses#update', as: 'update_course'
   delete '/courses/:id', to: 'courses#destroy', as: 'delete_course'

   get '/faculties/:id/courses', to: "faculty_courses#show"
   get '/faculties/:faculty_id/courses', to: 'faculty_courses#index', as: 'faculty_courses'
   get '/faculty_courses/new', to: "faculty_courses#new", as: 'new_course'
   post "/faculties/:faculty_id/courses", to: "faculty_courses#create"
   get '/faculties/:faculty_id/courses/filter', to: 'faculty_courses#filter', as: 'filter_faculty_courses'
   get '/faculties/:id/courses/new', to: 'faculty_courses#new', as: 'new_faculty_course'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :faculty, class_name: 'Faculty', foreign_key: 'faculty_id'
  has_many :faculty_courses

  # validates_presence_of :professor
  validates_presence_of :course_name
  # validates_presence_of :gen_ed
  validates_presence_of :credits
  validates_presence_of :start_date
  validates_presence_of :end_date

  def self.gen_ed_courses
    where(gen_ed: true)
  end
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :courses, foreign_key: 'faculty_id'
  has_many :faculty_courses

  validates_presence_of :name
  validates_presence_of :department
  validates_presence_of :email
  validates_presence_of :phone
  validates_presence_of :office_hours
  validates_presence_of :years_instructing

  def self.faculties_by_created_at
    Faculty.order(created_at: :desc)
  end

  def course_count 
    self.courses.count
  end

  def self.order_by_count
    Faculty.joins(:courses).group(:id).order('count(courses.id) desc')
  end

  def courses_alphabetical
    self.courses.order(:name)
  end

  def self.order_by_count
    Faculty.joins(:courses).group(:id).order('count(courses.id) desc')
  end
end

app/controllers/academic_controller.rb
class AcademicController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @gen_ed_courses = Course.gen_ed_courses
  end

  def new
    @faculty = Faculty.find(params[:faculty_id])
    @course = Course.new
  end

  def show
    @course = Course.find(params[:id])
    @faculty = @course.faculty
  end

  def create
    course = Course.find(params[:id])
    course.update({
      course_name: params[:course_name],
      professor: params[:professor],
      gen_ed: params[:gen_ed],
      credits: params[:credits],
      start_date: params[:start_date],
      end_date: params[:end_date]
    })

    course.save
    redirect_to "/faculties/#{faculty.id}/courses"
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    course = Course.find(params[:id])
    course.update({
      course_name: params[:course_name],
      professor: params[:professor],
      gen_ed: params[:gen_ed],
      credits: params[:credits],
      start_date: params[:start_date],
      end_date: params[:end_date]
    })

    course.save
    redirect_to "/courses/#{course.id}"
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to '/courses'
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def index
    if params[:sort] == 'true'
      @faculties = Faculty.faculties_by_created_at
    elsif
    @faculties = Faculty.order_by_count
    else
      @faculties = Faculty.all
    end
  end

  def new
    @faculty = Faculty.new
  end

  def show
    @faculty = Faculty.find(params[:id])
  end

  def create
    faculty = Faculty.new({
      name: params[:name],
      department: params[:department],
      email: params[:email],
      phone: params[:phone],
      office_hours: params[:office_hours],
      years_instructing: params[:years_instructing]
    })
    
    faculty.save
    redirect_to '/faculties'
  end

  def edit
    @faculty = Faculty.find(params[:id])
  end

  def update
    faculty = Faculty.find(params[:id])
    faculty.update({
      name: params[:name],
      department: params[:department],
      email: params[:email],
      phone: params[:phone],
      office_hours: params[:office_hours],
      years_instructing: params[:years_instructing]
    })

    faculty.save
    redirect_to "/faculties/#{faculty.id}"
  end

  def destroy
    @faculty = Faculty.find(params[:id])
    @faculty.courses.destroy_all  
    @faculty.destroy             
    
    redirect_to '/faculties'
  end
end

app/controllers/faculty_courses_controller.rb
class FacultyCoursesController < ApplicationController
  def index
    @faculty = Faculty.find(params[:faculty_id])
    if params[:sort_alpha] == 'true'
      @courses = @faculty.courses_alphabetical
    else
      @courses = @faculty.courses
    end
  end

  def filter
    @faculty = Faculty.find(params[:faculty_id])
    @courses = @faculty.courses

    threshold = params[:threshold].to_i
    @courses = @courses.where('credits > ?', threshold)

    render :index
  end
  
  def new
    @faculty = Faculty.find(params[:faculty_id])
    @course = Course.new
  end

  def create
    faculty = Faculty.find(params[:faculty_id])
    # binding.pry
    course = faculty.courses.build({
      course_name: params[:course_name],
      professor: params[:professor],
      gen_ed: params[:gen_ed],
      credits: params[:credits],
      start_date: params[:start_date],
      end_date: params[:end_date]
    })

    course.save
    
    redirect_to "/courses/#{course.id}"
  end

  def show
    @faculty = Faculty.find(params[:id])
    @courses = @faculty.courses
  end

 

  def new
    @faculty = Faculty.find(params[:id])
    @course = Course.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faculty_helper.rb
module FacultyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/academic/index.html.erb
<h1>Practical University Management</h1>

  <p><a href="/faculties">Our Faculty</a></p>
  <p><a href="/courses">Our Courses</a></p>

app/views/courses/edit.html.erb
<h1>Update Course</h1>
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></li></p>
<form action="<%= update_course_path(@course) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH" />
  <p>Enter new course details:</p>

  <div>
    <label for="course_name">Course Name:</label>
    <input type="text" name="[course_name]" id="course_name">
  </div>

<div>
    <label for="course_professor">Course Professor:</label>
    <input type="text" name="[professor]" id="professor">
  </div>

  <div>
    <label for="course_gen_ed">Fulfills General Education:</label>
    <input type="checkbox" name="[gen_ed]" id="gen_ed">
  </div>

  <div>
    <label for="course_credits">Credits:</label>
    <input type="number" name="[credits]" id="credits">
  </div>

  <div>
    <label for="course_start_date">Start Date:</label>
    <input type="text" name="[start_date]" id="start_date">
  </div>

  <div>
    <label for="course_end_date">End Date:</label>
    <input type="text" name="[end_date]" id="end_date">
  </div>

  <input type='submit' value='Update Course'/>
</form>

app/views/courses/index.html.erb
<h1>General Education Directory</h1>
<p><a href="/">University</a></p>
<a href="/faculties">Our Faculty</a>

<ul>
  <% @gen_ed_courses.each do |course| %>
  <div>
    <p><%= course.course_name %></p>
     <p><%= link_to 'View Course', course_path(course) %></p>
      <p><%= link_to '    Update Course ', edit_course_path(course) %></p>
    <form action="/courses/<%= course.id %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete Course"/>
    </form>
  </div>
  <% end %>
</ul>

app/views/courses/new.html.erb
<h1>Register Course</h1>
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></li></p>
<form action="<%= courses_path(@faculty) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <p>Enter course details:</p>

  <div>
    <label for="course_name">Course Name:</label>
    <input type="text" name="[course_name]" id="course_name">
  </div>

  <div>
    <label for="course_professor">Course Professor:</label>
    <input type="text" name="[professor]" id="professor">
  </div>

  <div>
    <label for="course_gen_ed">Fulfills General Education:</label>
    <input type="checkbox" name="[gen_ed]" id="gen_ed">
  </div>

  <div>
    <label for="course_credits">Credits:</label>
    <input type="number" name="[credits]" id="credits">
  </div>

  <div>
    <label for="course_start_date">Start Date:</label>
    <input type="text" name="[start_date]" id="start_date">
  </div>

  <div>
    <label for="course_end_date">End Date:</label>
    <input type="text" name="[end_date]" id="end_date">
  </div>

  <input type='submit' value='Register Course'/>
</form>

app/views/courses/show.html.erb
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></p>
<p><a href="<%= new_course_path(faculty_id: @faculty.id) %>">New Course</a></p>
<%= form_tag filter_faculty_courses_path(@faculty), method: :get do %>
    <%= label_tag 'threshold', 'Return classes with credits worth more than' %>
    <%= text_field_tag 'threshold' %>
    <%= submit_tag 'Filter' %>
<% end %>
<hr>
<form action="<%= delete_course_path(@course) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Course"/>
</form>
<hr>
<p><a href="<%= edit_course_path(@course) %>">Update Course</a></p>


<p><%= @course.course_name %></p>
<p><strong>Professor:</strong> <%= @course.professor %></p>
<p><strong>General Education Course:</strong> <%= @course.gen_ed %></p>
<p><strong>Credits:</strong> <%= @course.credits %></p>
<p><strong>Class Start Date:</strong> <%= @course.start_date %></p>
<p><strong>Class End Date:</strong> <%= @course.end_date %></p>

app/views/faculties/edit.html.erb
<h1>Update Faculty</h1>
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></li></p>
<form action="<%= update_faculty_path(@faculty) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH" />
  <p>Enter new faculty details:</p>

    <div>
    <label for="faculty_name">Name:</label>
    <input type="text" name="[name]" id="name">
  </div>

  <div>
    <label for="faculty_department">Department:</label>
    <input type="text" name="[department]" id="department">
  </div>

  <div>
    <label for="faculty_email">Email:</label>
    <input type="email" name="[email]" id="email">
  </div>

  <div>
    <label for="faculty_phone">Phone:</label>
    <input type="tel" name="[phone]" id="phone">
  </div>

  <div>
    <label for="faculty_office_hours">Office Hours:</label>
    <input type="checkbox" name="[office_hours]" id="office_hours">
  </div>

  <div>
    <label for="faculty_years_instructing">Years Instructing:</label>
    <input type="number" name="[years_instructing]" id="years_instructing">
  </div>

  <input type='submit' value='Create Faculty'/>
</form>

app/views/faculties/index.html.erb
<h1>Faculty Directory</h1>
<p><a href="/">University</a></p>
<p><a href="/courses">Our Courses</a></p>
<a href="<%= new_faculty_path %>">New Faculty</a>
<p><%= link_to "Sort by Number of Courses", faculties_path(sort_by: "courses") %></p>

  <ul>
    <% @faculties.each do |faculty| %>
    <div>
     <a href="/faculties/<%= faculty.id %>">
     <p><%= faculty.name %> <%= faculty.created_at%><%= link_to '  Update Faculty Member', edit_faculty_path(faculty) %><hr>

    <form action="/faculties/<%= faculty.id %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete Faculty"/>
    </form>

    <hr>
    </p>
    </a>
    </div>
    <% end %>
  </ul>

app/views/faculties/new.html.erb
<h1>Register faculty member</h1>
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></li></p>

<form action="/faculties" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Enter faculty member details:</p>

  <div>
    <label for="faculty_name">Name:</label>
    <input type="text" name="[name]" id="name">
  </div>

  <div>
    <label for="faculty_department">Department:</label>
    <input type="text" name="[department]" id="department">
  </div>

  <div>
    <label for="faculty_email">Email:</label>
    <input type="email" name="[email]" id="email">
  </div>

  <div>
    <label for="faculty_phone">Phone:</label>
    <input type="tel" name="[phone]" id="phone">
  </div>

  <div>
    <label for="faculty_office_hours">Office Hours:</label>
    <input type="checkbox" name="[office_hours]" id="office_hours">
  </div>

  <div>
    <label for="faculty_years_instructing">Years Instructing:</label>
    <input type="number" name="[years_instructing]" id="years_instructing">
  </div>

  <input type='submit' value='Create Faculty'/>
</form>

app/views/faculties/show.html.erb
<a href="/faculties">Our Faculty</a>
<p><a href="/courses">Our Courses</a></li></p>
<p><%= link_to 'View Faculty Member Courses', faculty_courses_path(@faculty) %></p>
<a href="/faculties/<%= @faculty.id %>/edit">Update Faculty</a>
<hr>
<form action="/faculties/<%= @faculty.id %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Faculty"/>
</form>
<hr>
<p><%= @faculty.name %></p>
<p><strong>Department:</strong> <%= @faculty.department %></p>
<p><strong>Courses Taught:</strong> <%= @faculty.courses.count %></p>
<p><strong>Email:</strong> <%= @faculty.email %></p>
<p><strong>Phone:</strong> <%= @faculty.phone %></p>
<p><strong>Office Hours open:</strong> <%= @faculty.office_hours %></p>
<p><strong>Has been instructing for <%= @faculty.years_instructing %> years!</p>

app/views/faculty_courses/index.html.erb
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></p>
<p><a href="<%= new_course_path(faculty_id: @faculty.id) %>">New Course</a></p>
<a href="/faculties/<%= @faculty.id %>/courses?sort=true">Alphabetical Sort</a>

<%= form_tag filter_faculty_courses_path(@faculty), method: :get do %>
    <%= label_tag 'threshold', 'Return classes with credits worth more than:' %>
    <%= text_field_tag 'threshold' %>
    <%= submit_tag 'Filter' %>
<% end %>

<hr>

<% @courses.each do |course| %>
<hr>
<p><a href="/courses/<%= @faculty.id %>/edit">Update Course</a></p>
<p><%= course.course_name %></p>
<p><strong>Professor:</strong> <%= course.professor %></p>
<p><strong>General Education Course:</strong> <%= course.gen_ed %></p>
<p><strong>Credits:</strong> <%= course.credits %></p>
<p><strong>Class Start Date:</strong> <%= course.start_date %></p>
<p><strong>Class End Date:</strong> <%= course.end_date %></p>
<% end %>

app/views/faculty_courses/new.html.erb
<h1>Register Course</h1>
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></li></p>
<form action="<%= faculty_courses_path(@faculty) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <p>Enter course details:</p>

  <div>
    <label for="course_name">Course Name:</label>
    <input type="text" name="[course_name]" id="course_name">
  </div>

  <div>
    <label for="course_professor">Course Professor:</label>
    <input type="text" name="[professor]" id="professor">
  </div>

  <div>
    <label for="course_gen_ed">Fulfills General Education:</label>
    <input type="checkbox" name="[gen_ed]" id="gen_ed">
  </div>

  <div>
    <label for="course_credits">Credits:</label>
    <input type="number" name="[credits]" id="credits">
  </div>

  <div>
    <label for="course_start_date">Start Date:</label>
    <input type="text" name="[start_date]" id="start_date">
  </div>

  <div>
    <label for="course_end_date">End Date:</label>
    <input type="text" name="[end_date]" id="end_date">
  </div>

  <input type='submit' value='Create Course'/>
</form>

app/views/faculty_courses/show.html.erb
<p><a href="/faculties">Our Faculty</a></p>
<p><a href="/courses">Our Courses</a></p>
<p><a href="/faculties/<%=@faculty.id %>/courses/new" %>New Course</a></p>
<a href="/faculties/<%= @faculty.id %>/courses?sort=true">Alphabetical Sort</a>

<%= form_tag filter_faculty_courses_path(@faculty), method: :get do %>
    <%= label_tag 'threshold', 'Return classes with credits worth more than:' %>
    <%= text_field_tag 'threshold' %>
    <%= submit_tag 'Filter' %>
<% end %>

<hr>

<% @courses.each do |course| %>
<hr>
<p><a href="/courses/<%= @faculty.id %>/edit">Update Course</a></p>
<p><%= course.course_name %></p>
<p><strong>Professor:</strong> <%= course.professor %></p>
<p><strong>General Education Course:</strong> <%= course.gen_ed %></p>
<p><strong>Credits:</strong> <%= course.credits %></p>
<p><strong>Class Start Date:</strong> <%= course.start_date %></p>
<p><strong>Class End Date:</strong> <%= course.end_date %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>